name: Build and Release Rust Binary for Windows, Linux, and macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: rust-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Install Rust cross
        run: cargo install cross
        if: ${{ matrix.os }} == "ubuntu-latest" 

      - name: Build for ${{ matrix.target }}
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest"  ];then
            cross build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
          
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            bin="target/${{ matrix.target }}/release/safe-rm.exe"
          else
            bin="target/${{ matrix.target }}/release/safe-rm"
          fi

          echo "BIN=$bin" >> $GITHUB_ENV

      - name: Mv binary
        shell: bash
        run: |
          pd="safe-rm-latest-${{ matrix.target }}"
          mkdir -p "$pd"
          mv "$BIN" "$pd"
          echo "pd=$pd" >> $GITHUB_ENV

      - name: Generate sha256 hash
        shell: bash
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            7z a "$pd.zip" "$pd"
            certutil -hashfile "$pd.zip" SHA256 > "$pd.zip.sha256"
            echo "ASSET=$pd.zip" >> $GITHUB_ENV
            echo "ASSET_SUM=$pd.zip.sha256" >> $GITHUB_ENV
          else
            tar -czvf "$pd.tar.gz" "$pd"
            shasum -a 256 "$pd.tar.gz" > "$pd.tar.gz.sha256"
            echo "ASSET=$pd.tar.gz" >> $GITHUB_ENV
            echo "ASSET_SUM=$pd.tar.gz.sha256" >> $GITHUB_ENV
          fi

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: |
            ${{ env.ASSET }}
            ${{ env.ASSET_SUM }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download All Binaries
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/**/*
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.SAFE_RM_RELEASE_TOKEN }}
